language: node_js
node_js:
- "6"

# Build the app and a docker image
script:
- npm run release
- ./scripts/docker-build.sh

# If successful, see if we need to publish also
after_success:
- ./scripts/travis-publish.sh

# Sudo required for doing docker build
sudo: required
services:
- docker

env:
  global:
  # Needed to compile native modules
  - CXX=g++-4.8
  # DOCKER_USER
  - secure: hL9GzKnAuHP130bLzB1nK9eF6bfPD4yFdQ1IdRRp7QDZ+AJ2MUw483w5Uacw6/VNk+KlItO9ySxkAI8gaBcxjxcp+TmFkmD0o4rRQixCoZiqlNeTCMmkx5J6KffNALiFBFPjOvVNXLEYh6lbyIsPJR0/eHGlhCbfpx9Ok9PxzVV4AtNNXVcqCl4hZFWPU8OX7nL0pyQ86MD1WiC/1nfTaE/9zaZ8M/qJhv558KmsSXnFN1eGrwVJLt8XPbZ5aKEvJq3cngwVJ3/hmMQnA6ScgANZFbFrDZo9gDmQLDAbGzQ4mg1wpmvdCGB9HEo14o+ZK3utmnURZDGLHcbgKitIp7fd+FyIktxF3h+hYm7yMV/P67ixLXWxay9F0XXkKF1CPhRU+uEijcWQY/txUItvfHJtDGQbHhChUPmzv2eTQD5QoevFByZ6c3ekQew6hgCPaOsV2FspQQ+XVtdjiiOzmWzeFux2Obc46K85BSyeEp9SjuTJ0772dFBZjWn9UP+M5B8THs4BNPhkSVhceHQBvv65H8DZYEazue0aJYwJhMd1qx5tq/3dXItyDVqxCj0J0LFI4TsFbSf4R+snYOxjc2dkpO1l9aZyLNBTbRn//MTki8o/tdIjAzNYKKWHHBWCYN7OU4Ej4t7XI/SKs3Wf131ebqLlTYU0ppJD7KQUvCU=
  # DOCKER_PASS
  - secure: hxakhOfACkkXcGc5T9cT0+a+ICw6X2ybsOXzJsgdju4QbdP0nD2iBSZCypDzfdzlF/y83yJGcSznegMega37ABomPd8BF04IJTY1ZSvfj8LiUiLLfo/YSsz68r/X1G/AxVmS/7x9x5xaCPMnCHaH2jK5Qiogawzlqgqw/h3EAQlnJyKdjwwmFpATUAuRJidQ/95pn4KYvERg3eZ7/DzqbAO4IRjSuxHRNqDsHXDR4xlBxXAwqt0SE9qfr8rIbuA264vwStltPi4RDfTWWBooxFTGWHpu7rS/N1xEg7+48Il0zckVqmbwMJeAfl8abXhqK5RRrpv77icHeqxi5bev/SL28PnNOhj5gXn6a4/1/JPuhzmKp1omNtlJsjjZhs7YidSOVQ2nEJjDoeQ9/d+Z+g6DosnkDbiS7+ijvIPD9SlRbyUlf7Z3wD8Hf91/fUgkaUoIVkBUFvW8i0fArfcWSIQErvixIGhj41yNOwIAheUFM4Y39NsuilJZZmqZ2Zh0/9AHUiY4fA7C6CajFC06CpjUCpDhb3m0uy1vJcUiG7Y3J6iTrRzaW8eqPnGBQcVTS7/dXPj3WtEP/xOF93sYeZMKE7hk489WAUJNLV9kmasSaVTzbu80kfM5Ml9m675dN3ztUAhaAPT0IqHnycngMBKe2Y7+EDalsDBsffOpO0k=
  # DOCKER_EMAIL
  - secure: MoDsYpEsVo+yC3+CDWsBqkmCL+k3pYPpnfVNrH4g8Hejk7qlVEfiTvJJtGU0SzajsQ6SR7r5cIekmiUe5kkxu/1zdynLOWbbP915r1+xTZ40a9QQy8cABr8M0JGa6cp2boXeMiTAcGXcl3elnUFQTuqKUupa1X+/G+tFS8XtX79mXOapnb9RdI+h2nPFp7rRcgqRlMQbfEVQmT4hWpeVaLFDOW+qpAIAJUGt3xzrlMllz8+0pfZfsn9eMlGVupnQBb9iXkPIxxc/o6i/tLYfrb0OgH/paa8xwOJfD3xVz0LkBMTNoqjUfBFm/wRxOziLxd0CZAoIGtnZ/wGKyJzIvd4dcVbFu9xqRnWp7JNSe/rfToFxdh2j7Kc1iqH6LzpFv/W3Hwk5fd0IUTGyf1v0cxp+Jx48swJzR90WDytHlAOZnfCqA0nWkF+aF9iniExIv7NBtwe+OB308s3nU+4pkVRKyh74PNTieVEkz8gANJRGcc3UrLu9GOoCuI7Jwk9eIB42Kpg+guhbNqXaB6QKgX8wCMqKCvmd/5ThcqUdK6Oz2LKByKXvsK0FbbFbPvmWj1C2v6KHYl4CmGyYs1yhLN/ZgDABQHT037vI96SLDhNwKF4g99ZufFUaMQicY0uprRZqjhjLq0M94Dsn+YxuHcdWnU/B1LrtXpUrGrUV6T0=
  # KILLRVIDEO_YOUTUBE_API_KEY
  - secure: mOlA5H9LWSQqxJvuwD5z1aTsr+QR1XL20chmJS2v3OHaowMawWmqbOvtRx2RWBWcuJG3oOu5w+DilYSphFvjXeZ311pU/k4cv99idQCfFAPXyIvLJPJde5oR1Cx0M0jpD8dQsNmhbFNte1ztl8Gip6+43Fsg9HjnCvZXGSGzCOJi2PQpF0arMnlXhEQPtPZPExvnvOLSvAa3R7mAZzLIBDNjzgKuM4CHi0WKYPW1bjcFxK5WK/+LU1EyHHwbUn6uCS54CNDTwiUQ9+BPpaF6y+nMZ6sSk+LwawXagnagqgRJZpzJ6MeDMQRVrEPGZ82WNfEOtgFksByr9/OwteilAOahBNqt9JS5w8nPCn+8/+W/E5T87cPLxiF1SiX6ru0tRKz2kXUDsPAAj17MC6iodaFNA6h8DxwY9qOe2r4eBKtE6JmpuuJdL8wIAWItVs70A36hR9eXueE0migw3Oh8BBywprriXUW2m63uFpglm/RPy040eRIhqdIMNd/q9yf+hEQy1wsGvIhAVIpmHxbbIxVn19++Z42GFWCHECveAjvrwxtkxsRnpxN9gGGC8lvwDLoT64VHVG7EJCOzqf7LWZWIYbPx9yBSqZVew5q6C6jToc25/Isk8Mjm5AG929o6JfaEb9h6e+CE3f0Wij3NYyncfntOnMN51KEEBP42//E=
# Also needed to compile native modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

# Cache node_modules between builds to try and speed things up
cache:
  directories:
  - node_modules
