# Loaded using https://github.com/lorenwest/node-config
# Can be overridden by creating a local.yaml file

loggingLevel: verbose

# Configuration injected into the client code when it's loaded
client:
  # The API key for talking to YouTube
  youTubeApiKey: REPLACE_WITH_YOUR_KEY

# Web Server settings
web:
  # Where to start the web server
  port: 3000
  # Express session settings
  session:
    name: killrvideo.sid
    secret: THE_INTERNET_IS_FULL_OF_CAT_VIDEOS
    cassandra:
      table: express_session

# Cassandra settings
cassandra:
  # The keyspace (will be created if it doesn't exist)
  keyspace: killrvideo_web
  # The replication string (i.e. after WITH REPLICATION) to use when creating the keyspace if it doesn't exist
  replication: "{ 'class' : 'SimpleStrategy', 'replication_factor' : 1 }"
  # The username and password needed to authenticate to the cluster.  
  # Either set these values here directly or use the KILLRVIDEO_DSE_USERNAME and KILLRVIDEO_DSE_PASSWORD environment variables. 
  dseUsername: null
  dsePassword: null

services:
  web:                    'web:3000'
  cassandra:              'dse'
  dse-search:             'dse:8983'
  UploadsService:         'backend:50101'
  RatingsService:         'backend:50101'
  CommentsService:        'backend:50101'
  SearchService:          'backend:50101'
  StatisticsService:      'backend:50101'
  VideoCatalogService:    'backend:50101'
  UserManagementService:  'backend:50101'
  SuggestedVideoService:  'backend:50101'
